### ISSUE TITLE
geckodriver not detected on Mac OS

### ISSUE THREAD

**Issue by jbrepogmailcom** [shardul08/Google-Trend-Wallpaper#9]
Hello, I have troubles to get it working on Mojave. I installed geckodriver yet I am still getting errors. With sudo and without sudo, same:

janbenes@Jans-Mac ~/Google-Trend-Wallpaper> brew install geckodriver
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/geckodriver-0.24.0.mojave.bottle.tar.gz
Already downloaded: /Users/janbenes/Library/Caches/Homebrew/downloads/8ab92ea1151f5b108dc35c68f6fe616f20414cf6ab7099e42f58b8dbfb169b6a--geckodriver-0.24.0.mojave.bottle.tar.gz
==> Pouring geckodriver-0.24.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/geckodriver/0.24.0: 7 files, 5.9MB
janbenes@Jans-Mac ~/Google-Trend-Wallpaper> sudo ./updateWallpaper.sh
Creating wallpaper...
ERROR: Install geckodriver, and make sure it's in your PATH
Something went wrong
You can raise an issue at https://github.com/shardul08/Google-Trend-Wallpaper/issues

**Comment by jbrepogmailcom** [comment]
Actually the problem can be more serious, because I am getting the error even after directly pointing to geckodriver:
browser = webdriver.Firefox(executable_path=r'/usr/local/bin/geckodriver')

**Comment by jbrepogmailcom** [comment]
Fixed by installing Firefox. Maybe you should list that as prerequisite... :-)

**Comment by shardul08** [comment]
Glad you could solve the issue. I will list firefox as a prerequisite.
